import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <nav style={{ display: "flex", justifyContent: "center", gap: "20px" }}>
        <a href="/" style={{ flex: 1, textAlign: "center" }}>Home</a>
          <a href="/table" style={{ flex: 1, textAlign: "center" }}>Table</a>
          <a href="/box" style={{ flex: 1, textAlign: "center" }}>Box</a>
        </nav>
        {children}
      </body>
    </html>
  );
}
