import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <nav
          style={{
            display: "flex",
            justifyContent: "center",
            gap: "40px", // 增加间距
            padding: "10px",
          }}
        >
          <a href="/" style={{ flex: 1, textAlign: "center", margin: "0 10px", backgroundColor: "red" }}>
            Home
          </a> <a href="/boxes" style={{ flex: 1, textAlign: "center", margin: "0 10px", backgroundColor: "red" }}>
          boxes
          </a>
           <a href="/task" style={{ flex: 1, textAlign: "center", margin: "0 10px", backgroundColor: "red" }}>
          task
          </a>
           <a href="/ipm" style={{ flex: 1, textAlign: "center", margin: "0 10px", backgroundColor: "red" }}>
          ipm
          </a>
        </nav>
        {children}
      </body>
    </html>
  );
}
